### ISSUE TITLE
【一些建议】

### ISSUE THREAD

**Issue by grantding** [kiwiflydream/yuque-helper#3]
文本加粗会被取消掉，加粗的话是重点字样，建议不对加粗的字体进行格式化保留原样

**Comment by grantding** [comment]
4级标题如果还是用四重编号“1.1.1.1 标题”会有些不美观，建议4级标题直接编号“1. 标题”

**Comment by kiwiflydream** [comment]
> 文本加粗会被取消掉，加粗的话是重点字样，建议不对加粗的字体进行格式化保留原样

是的，目前对于有样式的文本格式化有问题，还有链接，因为使用外部包的原因不太好改，后面打算有时间自行实现去替换

**Comment by kiwiflydream** [comment]
> 4级标题如果还是用四重编号“1.1.1.1 标题”会有些不美观，建议4级标题直接编号“1. 标题”

这个功能其实是按照 word 的功能设计的，有些人其实是想要这种效果的，不过的确挺丑，我先记下，后面加个开关去由使用者控制

![image](https://user-images.githubusercontent.com/13311001/104453481-7392ca80-55df-11eb-87df-5c6b5793f691.png)
